# Generated by Django 5.1 on 2024-08-30 13:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_pesticides_pesticideprocedure_pesticideingredients'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fertilizers',
            fields=[
                ('fertilizer_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FertilizersIngredients',
            fields=[
                ('ingredient_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(max_length=250)),
                ('fertilizer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.fertilizers')),
            ],
        ),
        migrations.CreateModel(
            name='FertilizersProcedure',
            fields=[
                ('procedure_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('procedure', models.CharField(max_length=500)),
                ('fertilizer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.fertilizers')),
            ],
        ),
    ]
