# Generated by Django 5.1 on 2024-08-30 13:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_fertilizers_fertilizersingredients_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fertilizers',
            options={'verbose_name_plural': 'Fertilizers'},
        ),
        migrations.AlterModelOptions(
            name='pesticides',
            options={'verbose_name_plural': 'Pesticides'},
        ),
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('appointment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('event_type', models.CharField(max_length=150)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('days', models.IntegerField(default=0)),
                ('notes', models.CharField(max_length=250)),
                ('status', models.CharField(default='PENDING', max_length=50)),
                ('date_created', models.DateTimeField()),
                ('date_modified', models.DateTimeField(blank=True, null=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='approver_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FertilizerFeedback',
            fields=[
                ('feedback_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('rating', models.IntegerField(default=0)),
                ('feedback', models.CharField(max_length=250)),
                ('timestamp', models.DateTimeField()),
                ('fertilizer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.fertilizers')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('subject', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=500)),
                ('sent_datetime', models.DateTimeField(blank=True, null=True)),
                ('date_created', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PesticideFeedback',
            fields=[
                ('feedback_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('rating', models.IntegerField(default=0)),
                ('feedback', models.CharField(max_length=250)),
                ('timestamp', models.DateTimeField()),
                ('pesticide', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.pesticides')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
