# Generated by Django 5.1 on 2024-09-01 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_fertilizers_options_alter_pesticides_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fertilizerfeedback',
            old_name='timestamp',
            new_name='datetime_posted',
        ),
    ]
