# Generated by Django 5.1 on 2024-09-01 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_timestamp_fertilizerfeedback_datetime_posted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pesticidefeedback',
            old_name='timestamp',
            new_name='datetime_posted',
        ),
    ]
