# Generated by Django 5.1 on 2024-09-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_timestamp_pesticidefeedback_datetime_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dp/'),
        ),
    ]
