# Generated by Django 5.1 on 2024-09-03 11:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandMeasure',
            fields=[
                ('land_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('abbr', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UOM',
            fields=[
                ('uom_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('abbr', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PesticideConversion',
            fields=[
                ('convert_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('uom_qty', models.IntegerField(default=0)),
                ('land_qty', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.landmeasure')),
                ('pesticide', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.pesticides')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.uom')),
            ],
        ),
    ]
