# Generated by Django 5.1 on 2024-09-03 11:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_landmeasure_uom_pesticideconversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='FertilizerConversion',
            fields=[
                ('convert_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('uom_qty', models.IntegerField(default=0)),
                ('land_qty', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
                ('fertilizer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.fertilizers')),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.landmeasure')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.uom')),
            ],
        ),
    ]
