# Generated by Django 5.1 on 2024-09-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_fertilizerconversion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointments',
            name='days',
        ),
        migrations.AddField(
            model_name='appointments',
            name='duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
