# Generated by Django 5.1 on 2024-09-15 12:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_appointments_days_appointments_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='fertilizers',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='fertilizer/'),
        ),
        migrations.AddField(
            model_name='pesticides',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pesticide/'),
        ),
        migrations.CreateModel(
            name='FertilizerSource',
            fields=[
                ('source_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('link', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.BooleanField(default=True)),
                ('fertilizer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.fertilizers')),
            ],
        ),
        migrations.CreateModel(
            name='PesticideSource',
            fields=[
                ('source_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('link', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.BooleanField(default=True)),
                ('pesticide', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.pesticides')),
            ],
        ),
    ]
